extends SceneTree
const BASIC=preload("res://scripts/basic_attack_3d.gd")
func _initialize():call_deferred("run")
func run():
	assert(GameData.enemy_level_for_stage(100,70,7)==100)
	assert(GameData.enemy_level_for_stage(100,110,7)==102)
	assert(GameData.enemy_level_for_stage(100,125,7)==105)
	assert(GameData.enemy_level_for_stage(100,500,7)==105)
	assert(GameData.enemy_stone_bonus({"hp":100,"attack":100},13)==GameData.enemy_stone_bonus({"hp":100000,"attack":100000},13))
	assert(is_equal_approx(GameData.heavy_stone_damage(8),3.4))
	assert(GameData.stone_cooldown_scale(0,8,0)>=.45)
	var q:=GameData.make_quiblet(0,60);var naked_hp:=GameData.max_hp(q)
	q.power_slot_stones[0]=GameData.normalize_power_stone({"type":"Health","power":300,"bonuses":[],"tier":3})
	assert(GameData.max_hp(q)==naked_hp+600)
	assert(GameData.team_equivalent_level([q])>60)
	assert(is_equal_approx(GameData.level_gap_factor(100,40),1.4) and is_equal_approx(GameData.level_gap_factor(40,100),.7))
	var arena:=Node3D.new();root.add_child(arena)
	var player:=QuibletActor3D.new();player.setup(q);arena.add_child(player);player.set_physics_process(false)
	var foe:=QuibletActor3D.new();foe.setup(GameData.make_quiblet(0,60),true);arena.add_child(foe);foe.set_physics_process(false)
	player.position=Vector3.ZERO;foe.position=Vector3(1.5,0,0);player.target=foe;foe.target=player
	var hp:=foe.current_hp;player.try_basic_attack(1.5)
	var shots:=arena.get_children().filter(func(n):return n.get_script()==BASIC)
	assert(shots.size()==1)
	for step in 10:shots[0]._physics_process(.01)
	assert(foe.current_hp<hp)
	player.try_basic_attack(1.5);assert(arena.get_children().filter(func(n):return n.get_script()==BASIC).size()==1)
	player.basic_cooldown=0;player.add_status("stun",1,1,foe);player.try_basic_attack(1.5)
	assert(arena.get_children().filter(func(n):return n.get_script()==BASIC).size()==1)
	player.statuses.clear()
	foe.data.moves=[{"name":"Rock Toss","slots":0,"stones":[]},{"name":"Quake","slots":0,"stones":[]}];foe.move_cooldowns.assign([0.0,0.0]);foe.move_cooldown_totals.assign([0.0,0.0])
	foe.try_use_best_move(1.5);assert(foe.move_cooldowns[0]>0 and foe.enemy_cast_recovery>0)
	foe.try_use_best_move(1.5);assert(foe.move_cooldowns[1]==0)
	# The new enemy recovery never delays explicit player moves.
	player.move_cooldowns.fill(0);player.enemy_cast_recovery=10;player.request_move(0,foe);assert(player.move_cooldowns[0]>0)
	foe.set_meta("level_boss",true);foe.enemy_cast_recovery=0;foe.boss_attacks=2
	foe.try_use_best_move(1.5);assert(foe.boss_warning_time>1.0)
	var before:=player.current_hp;foe.process_boss_pattern(.5);assert(player.current_hp==before)
	player.position=Vector3(10,0,0);foe.process_boss_pattern(1.0);assert(player.current_hp==before and foe.statuses.has("exposed"))
	player.position=Vector3(1.5,0,0);foe.current_hp=foe.max_hp*.4;foe.begin_boss_warning();foe.process_boss_pattern(1.5)
	assert(foe.boss_followup and foe.boss_warning_time>0)
	foe.process_boss_pattern(1.0);assert(foe.boss_warning_time==0 and foe.enemy_cast_recovery>0)
	foe.begin_boss_warning();foe.add_status("stun",1,1,player);foe.process_boss_pattern(.1);assert(foe.boss_warning_time==0)
	arena.free();await process_frame
	print("COMBAT_REBALANCE_OK: basic attacks, statuses, immediate moves, recovery, tension caps, equipment, boss warnings, dodge, phase and interruption")
	quit()
