extends SceneTree
func _initialize():call_deferred("run")
func run():
 var game=load("res://main.tscn").instantiate();root.add_child(game);await process_frame
 assert(game.save_access_blocked())
 game.roster.append(GameData.make_quiblet(1,5));game.roster.append(GameData.make_quiblet(2,5))
 game.team_indices.assign([2,0]);game.show_all_quiblets()
 assert(game.team_presets.size()==5)
 for i in 5:assert(game.content.find_child("TeamPreset%d"%i,true,false).text=="Preset %d"%(i+1))
 game.save_team_preset(0)
 var input=game.content.find_child("PresetName",true,false);input.text="Adventure";input.text_changed.emit("Adventure")
 var expected=game.team_presets[0].members.duplicate()
 var data=game.save_data();game.apply_save_data(data)
 assert(game.team_presets[0].name=="Adventure" and game.team_presets[0].members==expected)
 game.team_indices.assign([1]);game.apply_team_preset(0)
 assert(game.team_indices==[2,0])
 game.remove_roster_member(0)
 assert(game.team_presets[0].members==[expected[0]])
 game.apply_team_preset(0);assert(game.team_indices==[1])
 game.remove_roster_member(1)
 assert(game.team_presets[0].members.is_empty())
 var current=game.team_indices.duplicate();game.apply_team_preset(0);assert(game.team_indices==current)
 data.erase("team_presets");game.apply_save_data(data)
 assert(game.team_presets.size()==5 and game.team_presets[0].members.is_empty())
 print("Preset UI, names, in-memory persistence, ordering and missing-member cleanup passed")
 game.queue_free();await process_frame;quit()
