class_name ExpeditionStories
extends RefCounted

# Eight quiet journal beats for every expedition route. The sixteen main
# regions gradually fill the Camp Almanac; the four hidden regions are small
# side discoveries that echo the same themes of noticing, learning and sharing.
const STORIES := [
	[
		"With a blank Camp Almanac tucked safely away, the team sets out to learn what makes the Rolling Steppe feel like home.",
		"Bent grass points toward a ring of warm stones where tiny Quiblet tracks gather after rain.",
		"The team discovers that the stone ring catches dew and shares it slowly with the thirsty ground.",
		"Among the berry patches, every ripe fruit seems to grow where dew, shade, and patient footsteps meet.",
		"A wandering herd shows the team how many small trails can join without trampling the flowers between them.",
		"By following those gentle paths, the Quiblets sketch the first complete map for the Camp Almanac.",
		"The steppe guardian yields when the team proves it can cross the grass without disturbing its quiet rhythm.",
		"The first finished page says that a good journey begins by noticing where every neighbor finds room.",
	],
	[
		"A loose Almanac page escapes into the Windy Fields, and the team follows it between bowing seed heads.",
		"They learn that each gust carries a different seed depending on the height and shape of the grass.",
		"A flock of airy Quiblets teaches the team to pause in sheltered hollows before crossing the strongest currents.",
		"The berry grove thrives where drifting seeds settle together behind a low green ridge.",
		"The team repairs a line of windbreaks and watches young shoots take hold in their calm shadows.",
		"With the path steadied, the missing page sails neatly back into waiting hands.",
		"The field guardian parts the clouds with one last gust, revealing the creek country beyond.",
		"The Almanac records that even a restless wind can help a garden when someone gives it a welcoming place to land.",
	],
	[
		"In Winding Creeks, the team follows the escaped rainwater that once fed the Windy Fields.",
		"Pebbles beneath the clear current hum softly wherever two little streams meet.",
		"The Quiblets free a blocked channel and see fresh water return to a patch of curled reeds.",
		"Creekside berries reveal how roots hold the banks together while still leaving room for water to wander.",
		"A school of water Quiblets guides the team through crossings chosen for patience rather than speed.",
		"The team marks every spring and stepping stone so future travelers can drink without muddying the banks.",
		"The creek guardian opens the final channel, sending a bright ribbon of water toward distant cliffs.",
		"The new page teaches that a winding route can connect more lives than the shortest one.",
	],
	[
		"The Crooked Cliffs rise around the creek's source, their ledges stacked like the pages of an ancient notebook.",
		"Small fossils in the trail show which plants and Quiblets sheltered here long before Base Camp began.",
		"The team learns to read cracks, echoes, and falling dust before choosing a safe ledge.",
		"A sheltered berry terrace demonstrates how broken stone slowly becomes rich soil.",
		"Together the Quiblets brace a loose crossing without sealing the tiny homes inside the cliff.",
		"From the highest safe shelf, they copy the valley's long history into the Almanac.",
		"The cliff guardian lowers a stone bridge after the team respects every warning written in the rock.",
		"The page concludes that old ground is not still at all, but patiently becoming something new.",
	],
	[
		"Water and weathered stone meet in the Soggy Lowlands, where yesterday's leaves soften under every step.",
		"The team notices bright mushrooms returning nutrients to places that first seemed empty.",
		"A family of poison Quiblets shows which pools cleanse the marsh and which should be left undisturbed.",
		"The berry grove grows sweetest beside fallen logs that shelter roots, beetles, and cool water.",
		"The Quiblets reopen a slow marsh channel and let the lowlands breathe without draining them dry.",
		"New shoots appear behind the team, turning a muddy detour into the liveliest part of the map.",
		"The marsh guardian settles back into the reeds once the team recognizes decay as careful work rather than waste.",
		"The Almanac notes that endings feed beginnings when they are given time and space.",
	],
	[
		"The Lush Basin gathers water, soil, seeds, and shelter from every land the team has crossed.",
		"No single plant explains the abundance, so the Quiblets begin drawing the connections between them.",
		"They discover that shade trees, ground flowers, and burrowing neighbors each protect the others in turn.",
		"The crowded berry grove offers more fruit when the team clears only enough room for light to dapple through.",
		"A struggling sapling recovers after each Quiblet contributes one small kind of help.",
		"The team follows the basin's shared waterways to a cave sparkling beneath the roots.",
		"The basin guardian welcomes them onward after seeing that cooperation can be quieter than command.",
		"Their newest page says that a thriving place is made from many modest gifts exchanged again and again.",
	],
	[
		"Inside the Glimmering Grotto, reflected daylight turns drops of basin water into moving stars.",
		"The team finds that different crystals brighten when different Quiblets stand nearby.",
		"By arranging mirrors of wet stone, they carry a narrow beam into a long-dark passage.",
		"Pale cave berries glow just enough to reveal the small creatures that tend their roots.",
		"The Quiblets learn that the grotto's finest light is borrowed, redirected, and freely shared.",
		"A crystal wall reflects the completed Almanac pages as a single colorful path.",
		"The grotto guardian adds one clear shard to the journal and points toward the snowy north.",
		"The page records that understanding grows brighter when many different viewpoints meet.",
	],
	[
		"On the Shivering Shelf, the crystal shard catches a pale sun that barely rises above the ice.",
		"The team slows down enough to hear water moving safely beneath the frozen surface.",
		"Tracks in fresh snow teach the Quiblets when to follow, when to wait, and when to turn aside.",
		"Frostberries ripen in sheltered pockets where the cold has remained steady rather than harsh.",
		"The team builds small wind screens and rests while a white squall passes harmlessly overhead.",
		"At dawn, the patient route reveals a warm current leading away from the shelf.",
		"The ice guardian allows passage after the Quiblets choose calm timing over a hurried crossing.",
		"The Almanac gains a quiet reminder that waiting can be a useful part of moving forward.",
	],
	[
		"The warm current ends beneath the Parched Plains, where every drop and patch of shade is carefully used.",
		"The team watches desert plants fold their leaves at noon and open them again in the cool evening.",
		"A line of tiny footprints leads to a shared seep hidden under a sun-warmed stone.",
		"The berry grove offers sparse but vivid fruit, each one protected by a neighborhood of thorns.",
		"The Quiblets mend shallow channels that spread rare rain without letting it rush away.",
		"By traveling at dusk, they find a comfortable route toward the high country.",
		"The plains guardian shares a stored seed when the team leaves every water hollow fuller than it found it.",
		"The page teaches that having less can sharpen care without shrinking generosity.",
	],
	[
		"The Highland Peaks lift the team above the plains, where familiar lands fit together in a surprising new pattern.",
		"Mountain gusts carry scents from valleys too distant to see from the trail below.",
		"The Quiblets place small markers where cloud, stone, and bird paths repeatedly cross.",
		"High berries cluster on sunny ledges that can be reached only by sharing the safest route.",
		"From one ridge, the team spots gaps in earlier maps and gently corrects the Almanac.",
		"A chain of friendly calls carries their observations from peak to peak faster than any traveler.",
		"The highland guardian answers the final call and reveals a descending path into the moor.",
		"The new page says that distance can make the whole journey clearer without making small details less important.",
	],
	[
		"Misty footprints in the Muddy Moor invite the team to read stories left by travelers they may never meet.",
		"Some tracks circle feeding places while others form patient lines toward shelter and clean water.",
		"The Quiblets learn to distinguish a lost trail from a creature simply taking its time.",
		"Moor berries grow beside old prints, nourished by paths that have rested long enough to turn green again.",
		"The team lays stepping stones where heavy traffic would otherwise widen the mud.",
		"A half-faded route leads them to salt air and the sound of a distant tide.",
		"The moor guardian adds its own footprint to the map and leaves the way to the coast open.",
		"The Almanac records that every path tells a story, even when its traveler stays unseen.",
	],
	[
		"At the Foaming Fjord, the tide gathers messages from streams, marshes, and snowy shelves into one bright inlet.",
		"The team learns the rhythm of safe crossings by watching foam curl around the rocks.",
		"Drifting shells carry seeds and tiny passengers between shores that seem far apart.",
		"Salt-sweet berries flourish above the tide line where spray reaches but waves do not.",
		"The Quiblets help clear a quiet cove where traveling creatures can rest before the next current.",
		"They seal copies of several Almanac pages against the mist so distant camps can share them.",
		"The fjord guardian sends those pages outward on the turning tide and points toward a shadowed forest.",
		"The journal notes that knowledge, like water, becomes more useful when it is allowed to travel.",
	],
	[
		"The Gloomy Glade receives the fjord's stories beneath a canopy where daylight arrives in small green pieces.",
		"The team discovers night-blooming flowers by following gentle scents instead of bright landmarks.",
		"Quiet psychic Quiblets teach them to notice rustles, echoes, and feelings that a map cannot show.",
		"Dusky berries ripen where moths visit after the daytime gatherers have gone to sleep.",
		"The Quiblets hang tiny reflected markers that guide travelers without waking the glade.",
		"In the deepest shade, they find a seedling grown from one of the Windy Fields' wandering seeds.",
		"The glade guardian brightens the exit once the team proves that darkness can be explored without being chased away.",
		"The Almanac gains a page about senses that awaken only when the world becomes quiet.",
	],
	[
		"Beyond the glade, the Looming Lowlands stretch beneath tall reeds that turn wind and rain into shelter.",
		"The team finds many small homes raised just above the seasonal flood marks.",
		"Earth Quiblets demonstrate how woven roots can hold a bank without making it rigid.",
		"The berry grove shelters beneath arching reeds where every nest receives both shade and an open view.",
		"Together the travelers mend a communal resting mound before the next soft rain arrives.",
		"Warm lights appear across the lowlands as neighbors use the Almanac's shared designs.",
		"The lowland guardian opens the eastern trail after seeing the team build shelter for creatures it has not met.",
		"The page concludes that a safe home can be an invitation as well as a wall.",
	],
	[
		"Across the Distant Downs, small sparks flicker in the grass like signals answering the lowland lights.",
		"The team meets electric Quiblets that communicate through quick flashes, taps, and humming stones.",
		"By matching those gentle patterns, the travelers learn of a meadow missing from every ordinary map.",
		"Charged berries brighten one after another, tracing a path through the rolling hills.",
		"The Quiblets arrange safe conductors so summer static can dance without scorching the grass.",
		"Each signal adds a symbol to the Almanac that can be understood without words.",
		"The downs guardian releases one long golden flash toward the hidden meadow beyond the horizon.",
		"The journal records that a friendly message needs only a pattern and someone willing to notice it.",
	],
	[
		"The golden signal leads into Mystery Meadow, where traces of every earlier land appear side by side.",
		"The team recognizes wind-borne seeds, creek pebbles, cliff soil, marsh mushrooms, and a shard of grotto light.",
		"Rather than solving the meadow at once, the Quiblets compare what each traveler notices first.",
		"Its berry grove changes flavor with the weather, preserving a small taste of the whole journey.",
		"The team completes the Camp Almanac by drawing connections that no single page could contain.",
		"A blank page at the back reveals itself in moonlight, waiting for discoveries no map has named yet.",
		"The meadow guardian closes the old journey with a peaceful bow and opens a dozen little paths onward.",
		"Back at camp, the Quiblets understand that the Almanac is complete only when it always has room for one more wonder.",
	],
	[
		"A side breeze from the Windy Fields reveals the hidden entrance to the Rustling Thicket.",
		"Leaves with different voices help the team tell open paths from homes best left alone.",
		"The Quiblets follow seed-carrying breezes through tunnels woven by branches rather than cut through them.",
		"Thicket berries hide at many heights, inviting every member of the team to notice a different layer.",
		"A fallen limb becomes a bridge once the travelers roll it only as far as the roots allow.",
		"The rustling canopy repeats the team's footsteps until they learn to move with its rhythm.",
		"The thicket guardian shares a feather-light leaf after the winding passage is mapped gently.",
		"This side page celebrates places that reveal themselves slowly to considerate visitors.",
	],
	[
		"A low stream from the Lush Basin opens onto the hidden Pebbled Shoals.",
		"Every tide rearranges the colored stones without erasing the beach's familiar shape.",
		"The team learns which pools welcome careful exploration and which are tiny worlds needing rest.",
		"Shore berries grow behind pebble ridges rebuilt a little differently by each wave.",
		"The Quiblets return stranded shells to water and leave the best skipping stones where they found them.",
		"At sunset, wet pebbles reflect the same colors as the basin flowers upstream.",
		"The shoal guardian traces a spiral in the sand before the next tide smooths it away.",
		"This side page remembers that change can preserve a place as surely as stillness.",
	],
	[
		"Behind a narrow pass in the Highland Peaks, the team discovers the hidden Rocky Ravine.",
		"Echoes reveal ledges and side passages that cannot be seen from the ravine floor.",
		"Earth Quiblets show how loose stones settle into strong arches when each one finds its fit.",
		"Ravine berries flourish in pockets where morning sun and evening cool arrive in equal measure.",
		"The travelers clear only the stones blocking the stream and leave the natural steps intact.",
		"Their calls return with new tones as the repaired waterway changes the shape of the echo.",
		"The ravine guardian rolls aside one final boulder and reveals a peaceful overlook.",
		"This side page notes that strength often comes from fitting together rather than standing alone.",
	],
	[
		"A trail of warm lantern seeds from the Looming Lowlands leads into the hidden Golden Grove.",
		"The grove's leaves store sunlight and release a soft glow long after evening arrives.",
		"The team follows pollinators between golden flowers, learning the garden's unhurried schedule.",
		"Sunlit berries ripen in shared clusters that brighten whenever a neighbor is gathered carefully.",
		"The Quiblets open small windows in the canopy so new growth can join the older trees.",
		"Every repaired clearing adds another warm light to the route back toward camp.",
		"The grove guardian offers a fallen golden leaf once the last young sapling has room to grow.",
		"This side page keeps a little stored sunlight for any traveler who needs encouragement later.",
	],
]

static func story(area_index: int, node_index: int) -> String:
	var area := clampi(area_index, 0, STORIES.size() - 1)
	var node := clampi(node_index, 0, STORIES[area].size() - 1)
	return STORIES[area][node]
