class_name MoveBehaviors
extends RefCounted

# Gameplay definitions, separate from names, artwork, and base damage/cooldowns.
# Distances are world units; times are seconds. Each named move has an explicit
# delivery method and effect, rather than falling back to a generic attack.
const PROFILES:={
	"Shock Bite":{"mode": "dash", "speed": 11.0, "radius": 0.8, "physical": true, "stop_at_target": true, "status": "paralyzed", "status_duration": 1.0, "status_chance": 0.2},
	"Latch":{"mode": "contact", "attach": true, "duration": 2.4, "tick": 0.4, "status": "slow", "status_duration": 0.65, "amount": 0.5, "physical": true},
	"Live Wire":{"mode": "contact", "duration": 2.5, "tick": 0.3},
	"Static Pulse":{"mode": "area", "anchor": "self", "radius": 2.8, "status": "paralyzed", "status_duration": 1.0, "status_chance": 0.2},
	"Tail Zap":{"mode": "cone", "angle": 2.0, "rear": true, "physical": true},
	"Discharge":{"mode": "area", "anchor": "self", "radius": 4.3, "delay": 0.7},
	"Slither":{"mode": "dash", "speed": 15.0, "radius": 0.55, "no_damage": true},
	"Shock Toss":{"mode": "contact", "attach": true, "restrain": true, "duration": 0.75, "tick": 0.4, "release_knockback": 4.0, "physical": true},
	"Amp Drain":{"mode": "contact", "attach": true, "duration": 3.0, "tick": 0.4, "leech": 0.65},
	"Zap":{"mode": "projectile", "speed": 22.0, "radius": 0.18},
	"Shock Touch":{"mode": "maneuver", "pattern": "touch", "speed": 20.0, "radius": 0.8},
	"Zip":{"mode": "dash", "speed": 35.0, "radius": 0.7},
	"Jolt Kick":{"mode": "dash", "speed": 15.0, "radius": 0.8, "stop_at_target": true, "physical": true, "knockback": 1.8, "leap": true},
	"Flashstep":{"mode": "maneuver", "pattern": "side", "speed": 25.0, "radius": 0.85},
	"Friction Dash":{"mode": "dash", "speed": 22.0, "radius": 0.8, "end_burst": 2.8, "burst_scale": 1.5, "stop_on_hit": true},
	"Thunderclap":{"mode": "area", "anchor": "self", "radius": 3.1, "interrupt": true},
	"Zigzag":{"mode": "maneuver", "pattern": "zigzag", "speed": 28.0, "radius": 0.85},
	"Horn Zap":{"mode": "cone", "angle": 0.5, "physical": true, "status": "paralyzed", "status_duration": 1.0, "status_chance": 0.3},
	"Spark Ram":{"mode": "dash", "speed": 11.0, "radius": 1.0, "physical": true, "knockback": 2.2},
	"Clamp":{"mode": "contact", "attach": true, "restrain": true, "duration": 1.5, "tick": 0.5, "physical": true},
	"Ground Scrape":{"mode": "dash", "speed": 10.0, "radius": 1.35, "physical": true, "visual": "sparks"},
	"Grounded":{"mode": "buff", "status": "grounded", "duration": 5.0, "amount": 0.9},
	"Horn Lift":{"mode": "cone", "angle": 0.5, "physical": true, "launch": 2.5},
	"Shock Clamp":{"mode": "contact", "attach": true, "restrain": true, "duration": 2.5, "tick": 0.4},
	"Tentacle Zap":{"mode": "line", "radius": 0.4, "visual": "vine"},
	"Nerve Sting":{"mode": "line", "radius": 0.3, "status": "paralyzed", "status_duration": 1.5, "status_chance": 0.75, "visual": "vine"},
	"Shock Net":{"mode": "field", "anchor": "self_follow", "radius": 3.5, "duration": 3.5, "tick": 0.4, "status": "slow", "status_duration": 0.7, "amount": 0.5, "visual": "sparks"},
	"Jelly Drift":{"mode": "dash", "speed": 12.0, "radius": 0.6, "no_damage": true},
	"Jolt Grab":{"mode": "contact", "restrain": true, "duration": 2.5, "tick": 0.4},
	"Smog":{"mode": "field", "anchor": "target", "radius": 2.6, "duration": 3.0, "tick": 0.5, "status": "smoke", "status_duration": 2.0, "amount": 0.5, "no_damage": true, "visual": "cloud"},
	"Toxic Drift":{"mode": "dash", "speed": 5.0, "radius": 1.3, "trail": 3.0, "trail_radius": 1.5, "poison": 3.0, "poison_chance": 0.3},
	"Contaminate":{"mode": "field", "anchor": "target_follow", "radius": 0.65, "duration": 5.0, "tick": 0.5, "status": "contaminated", "status_duration": 2.0, "amount": 0.4, "visual": "cloud"},
	"Fume Shot":{"mode": "projectile", "speed": 13.0, "radius": 0.3, "splash": 2.1, "visual": "cloud"},
	"Pressure Cloud":{"mode": "area", "anchor": "self", "radius": 3.3, "delay": 0.25, "knockback": 4.0, "visual": "cloud"},
	"Miasmum":{"mode": "field", "anchor": "self_follow", "radius": 5.7, "duration": 6.0, "tick": 0.5, "poison": 5.0, "poison_chance": 0.8, "visual": "cloud"},
	"Toxic Touch":{"mode": "dash", "speed": 10.0, "radius": 0.7, "stop_at_target": true, "physical": true, "poison": 4.0, "poison_chance": 0.4},
	"Sludge Wave":{"mode": "area", "anchor": "self", "radius": 3.0, "poison": 4.0, "poison_chance": 0.4},
	"Slime Slide":{"mode": "dash", "speed": 13.0, "radius": 0.85, "physical": true},
	"Slip Slime":{"mode": "area", "anchor": "target", "radius": 1.0, "status": "slippery", "status_duration": 3.5, "amount": 0.8},
	"Poison Coat":{"mode": "field", "anchor": "self_follow", "radius": 1.25, "duration": 5.0, "tick": 0.5, "poison": 3.0, "poison_chance": 0.35},
	"Acid Splash":{"mode": "cone", "angle": 0.9},
	"Slick Escape":{"mode": "dash", "speed": 15.0, "radius": 0.7, "trail": 4.0, "escape": true, "poison": 3.0, "poison_chance": 0.35, "status": "slow", "status_duration": 2.0, "amount": 0.45},
	"Gulp":{"mode": "cone", "angle": 0.5, "physical": true},
	"Slosh":{"mode": "cone", "angle": 2.2, "poison": 3.0},
	"Acid Spray":{"mode": "cone", "angle": 0.65, "status": "defense_down", "status_duration": 4.0, "amount": 0.25},
	"Nectar":{"mode": "area", "anchor": "self", "radius": 2.7, "status": "slow", "status_duration": 4.0, "amount": 0.5, "no_damage": true},
	"Belch":{"mode": "cone", "angle": 0.8, "knockback": 3.5, "visual": "cloud"},
	"Sour Shot":{"mode": "projectile", "speed": 21.0, "radius": 0.22},
	"Dribble":{"mode": "field", "anchor": "self", "radius": 0.85, "duration": 4.0, "tick": 0.4, "poison": 2.0, "patch_count": 5, "patch_spread": 1.6},
	"Lid Smack":{"mode": "cone", "angle": 0.45, "physical": true, "knockback": 0.6},
	"Rollout":{"mode": "dash", "speed": 9.0, "radius": 0.95, "physical": true, "knockback": 1.6, "curl": true},
	"Unfurl":{"mode": "area", "anchor": "self", "radius": 3.0, "delay": 0.45, "physical": true, "knockback": 3.2, "curl": true},
	"Rockslide":{"mode": "projectile", "speed": 11.0, "radius": 0.35, "pierce": true, "projectile_count": 5, "spread": 0.18},
	"Pound":{"mode": "area", "anchor": "self", "radius": 4.0, "delay": 0.85, "physical": true, "status": "stun", "status_duration": 1.5, "status_chance": 0.35, "jump": true, "knockback": 0.8},
	"Rolling Smash":{"mode": "dash", "speed": 12.0, "radius": 0.9, "physical": true, "knockback": 3.0, "stop_at_target": true, "curl": true},
	"Stone Skip":{"mode": "projectile", "speed": 8.0, "radius": 0.4, "pierce": true, "repeat_hit": 0.18, "skip": true},
	"Rock Ring":{"mode": "area", "anchor": "self", "radius": 3.2, "delay": 0.25, "physical": true, "visual": "thorns"},
	"Pebble Spray":{"mode": "projectile", "speed": 16.0, "radius": 0.16, "projectile_count": 7, "spread": 0.18},
	"Water Shot":{"mode":"projectile","speed":16.0,"radius":.18},
	"Water Jet":{"mode":"beam","duration":1.8,"tick":.2,"radius":.32},
	"Splash Dash":{"mode":"dash","speed":12.0,"radius":.65,"physical":true},
	"Backwash":{"mode":"cone","angle":.65,"knockback":2.6},
	"Water Burst":{"mode":"area","anchor":"self","radius":3.0,"knockback":.5},
	"Rain Drop":{"mode":"area","anchor":"target","radius":1.7,"delay":.85,"visual":"rain"},
	"Hydro Shot":{"mode":"projectile","speed":14.0,"radius":.5,"pierce":true},
	"Breaker":{"mode":"cone","angle":.9,"delay":.35,"knockback":1.1,"visual":"wave"},
	"Riptide":{"mode":"wave","speed":3.6,"width":1.8,"radius":.55,"carry":true,"knockback":.5},
	"Undertow":{"mode":"area","anchor":"self","radius":3.2,"pull":2.4},
	"Whirlpool":{"mode":"field","anchor":"self_follow","radius":3.0,"duration":3.0,"tick":.35,"pull":.45,"swirl":.6},
	"Wave Rush":{"mode":"dash","speed":8.0,"radius":1.2,"knockback":1.0,"physical":true,"visual":"wave"},
	"Tidal Wave":{"mode":"wave","speed":4.5,"width":5.0,"radius":.65,"carry":true,"knockback":.8},
	"Water Spout":{"mode":"area","anchor":"target","radius":1.0,"delay":.4,"launch":1.8,"visual":"pillar"},
	"Spray":{"mode":"cone","angle":1.15},
	"Downpour":{"mode":"field","anchor":"target","radius":2.7,"delay":.4,"duration":4.0,"tick":.4,"visual":"rain"},
	"Tsunami":{"mode":"wave","speed":4.0,"width":8.0,"radius":1.0,"carry":true,"knockback":1.2},
	"Leaf Shot":{"mode":"projectile","speed":18.0,"radius":.18,"visual":"leaf"},
	"Vine Whip":{"mode":"cone","angle":1.15,"physical":true,"visual":"vine"},
	"Vine Spear":{"mode":"line","radius":.3,"physical":true,"visual":"vine"},
	"Vine Grab":{"mode":"projectile","speed":12.0,"radius":.22,"pull":2.8,"visual":"vine"},
	"Rootbind":{"mode":"area","anchor":"target","radius":.7,"status":"root","status_duration":3.0,"visual":"roots"},
	"Thorn Burst":{"mode":"area","anchor":"target","radius":1.9,"delay":.35,"visual":"thorns"},
	"Sprout":{"mode":"area","anchor":"target","radius":.7,"delay":.3,"launch":.8,"visual":"plant"},
	"Seed Pop":{"mode":"projectile","speed":8.0,"radius":.2,"splash":1.5,"fuse":.65,"visual":"seed"},
	"Healing Bloom":{"mode":"heal_field","anchor":"self","radius":3.0,"duration":4.0,"tick":.5,"amount":.055,"visual":"flower"},
	"Pollen Puff":{"mode":"heal","radius":3.0,"amount":.25},
	"Soothing Scent":{"mode":"cleanse"},
	"Overgrowth":{"mode":"area","anchor":"target","radius":3.3,"delay":.5,"knockback":2.0,"visual":"plant"},
	"Spore Cloud":{"mode":"field","anchor":"target","radius":2.2,"duration":3.5,"tick":.5,"status":"stun","status_duration":1.0,"visual":"cloud"},
	"Thorn Armor":{"mode":"buff","status":"thorns","duration":5.0,"amount":.4},
	"Seed Mine":{"mode":"mine","anchor":"self","radius":2.0,"trigger_radius":1.3,"delay":.45,"duration":10.0,"visual":"seed"},
	"Root Slam":{"mode":"area","anchor":"target","radius":2.5,"delay":.85,"physical":true,"knockback":.7,"visual":"root_slam"},
	"Vine Swing":{"mode":"dash","speed":15.0,"radius":.45,"physical":true,"stop_at_target":true,"visual":"vine"},
	"Growth Spurt":{"mode":"buff","status":"growth","duration":6.0,"amount":1.5},
	"Cocoon":{"mode":"buff","status":"cocoon","duration":4.0,"amount":.125},
	"Leech Bloom":{"mode":"projectile","speed":8.0,"radius":.25,"leech":.5,"status":"leech","status_duration":3.0,"visual":"flower"},
	"Last Bloom":{"mode":"heal","radius":4.5,"amount":.6,"low_hp":.35},
	"Fireball":{"mode":"projectile","speed":11.0,"radius":.3,"splash":1.6},
	"Flame Burst":{"mode":"cone","angle":.6},
	"Spark Burst":{"mode":"area","anchor":"self","radius":2.6},
	"Flare":{"mode":"area","anchor":"self","radius":3.0,"knockback":2.0},
	"Flame Dash":{"mode":"dash","speed":12.0,"radius":.75,"physical":true,"burn":3.0},
	"Blazing Rush":{"mode":"dash","speed":9.0,"radius":1.1,"physical":true,"knockback":1.8,"burn":3.0},
	"Flame Wave":{"mode":"wave","speed":5.0,"width":4.5,"radius":.6,"burn":3.0},
	"Firestorm":{"mode":"field","anchor":"target","radius":3.2,"duration":3.0,"tick":.45,"burn":3.0,"visual":"eruptions"},
	"Inferno":{"mode":"area","anchor":"self","radius":4.8,"delay":.6,"knockback":1.2,"burn":4.0},
	"Flame Pillar":{"mode":"area","anchor":"target","radius":1.15,"delay":.45,"burn":3.0,"visual":"pillar"},
	"Meteor Ember":{"mode":"area","anchor":"target","radius":2.3,"delay":1.0,"burn":3.0,"visual":"meteor"},
	"Flame Spin":{"mode":"field","anchor":"self_follow","radius":2.6,"duration":2.4,"tick":.3,"burn":2.0,"spin":true},
	"Heat Haze":{"mode":"buff","status":"evade","duration":5.0,"amount":.45},
	"Ignite":{"mode":"projectile","speed":12.0,"radius":.22,"burn":4.0,"direct_scale":.2},
	"Fire Mine":{"mode":"mine","anchor":"self","radius":2.3,"trigger_radius":1.3,"delay":.45,"duration":10.0,"burn":3.0,"visual":"ember"},
	"Smoke Cloud":{"mode":"field","anchor":"target","radius":2.8,"duration":4.0,"tick":.4,"status":"smoke","status_duration":1.0,"visual":"cloud"},
	"Cauterize":{"mode":"cleanse","self_cost":.06},
	"Firework":{"mode":"firework","anchor":"target","radius":3.2,"delay":.7,"duration":1.2,"tick":.2,"burn":3.0},
	"Mind Jab":{"mode":"projectile","speed":15.0,"radius":.3},
	"Psycho Punch":{"mode":"projectile","speed":6.0,"radius":.7,"splash":1.8,"knockback":2.6},
	"Fist Barrage":{"mode":"field","anchor":"target","radius":1.3,"duration":1.3,"tick":.16},
	"Helping Hand":{"mode":"buff","status":"empower","duration":8.0,"amount":1.35,"ally":true},
	"Psy Bolt":{"mode":"projectile","speed":15.0,"radius":.28},
	"Telekinesis":{"mode":"area","anchor":"target","radius":1.0,"delay":.35,"launch":1.6,"visual":"pillar"},
	"Psychic Push":{"mode":"cone","angle":.7,"knockback":2.4},
	"Psychic Pull":{"mode":"projectile","speed":12.0,"radius":.24,"pull":2.6},
	"Psy Barrier":{"mode":"buff","status":"shield","duration":6.0,"amount":.4},
	"Gravity Well":{"mode":"field","anchor":"target","radius":2.8,"duration":3.0,"tick":.4,"pull":.5,"swirl":.3,"visual":"cloud"},
	"Mind Squeeze":{"mode":"field","anchor":"target","radius":1.2,"duration":1.4,"tick":.18},
	"Psy Wall":{"mode":"field","anchor":"target","radius":2.0,"duration":3.0,"tick":.5,"status":"slow","status_duration":1.5,"amount":.45,"visual":"cloud"},
	"Psy Bounce":{"mode":"dash","speed":13.0,"radius":.9,"physical":true},
	"Puff Grab":{"mode":"area","anchor":"target","radius":1.2,"delay":.4,"launch":2.0,"knockback":2.2,"visual":"pillar"},
	"Mind Pop":{"mode":"area","anchor":"self","radius":4.6,"delay":.6,"knockback":2.6},
	"Quake":{"mode":"area","anchor":"self","radius":3.2,"knockback":1.4},
	"Rock Toss":{"mode":"projectile","speed":11.0,"radius":.28,"splash":1.4},
	"Pitfall":{"mode":"mine","anchor":"self","radius":1.4,"trigger_radius":1.3,"delay":.4,"duration":10.0,"status":"root","status_duration":2.5},
	"Sinkhole":{"mode":"area","anchor":"target","radius":2.6,"delay":.4,"pull":2.2,"visual":"cloud"},
	"Burrow":{"mode":"buff","status":"evade","duration":5.0,"amount":.5},
	"Groundbreaker":{"mode":"line","radius":.35,"physical":true},
	"Dust Cloud":{"mode":"field","anchor":"target","radius":2.6,"duration":3.5,"tick":.5,"status":"smoke","status_duration":1.0,"visual":"cloud"},
	"Mud Shot":{"mode":"projectile","speed":12.0,"radius":.24,"status":"slow","status_duration":2.0,"amount":.4},
	"Dig Punch":{"mode":"area","anchor":"target","radius":1.1,"delay":.5,"launch":1.8,"physical":true,"visual":"pillar"},
	"Dust-Up":{"mode":"area","anchor":"self","radius":3.0,"delay":.3,"status":"confuse","status_duration":2.5,"amount":.5},
	"Tunneling Charge":{"mode":"dash","speed":11.0,"radius":1.0,"physical":true},
	"Stone Wall":{"mode":"field","anchor":"target","radius":2.0,"duration":3.0,"tick":.5,"status":"slow","status_duration":1.5,"amount":.4,"visual":"cloud"},
	"Rock Armor":{"mode":"buff","status":"shield","duration":6.0,"amount":.45},
	"Boulder Roll":{"mode":"dash","speed":9.0,"radius":1.1,"physical":true,"knockback":1.4},
	"Earth Pillar":{"mode":"area","anchor":"target","radius":1.0,"delay":.4,"launch":1.8,"visual":"pillar"},
	"Stone Spikes":{"mode":"area","anchor":"target","radius":1.9,"delay":.35,"visual":"thorns"},
	"Brace":{"mode":"buff","status":"shield","duration":6.0,"amount":.5},
	"Crush":{"mode":"area","anchor":"target","radius":1.6,"delay":.45,"knockback":.6,"physical":true},
	"Barricade":{"mode":"field","anchor":"target","radius":2.2,"duration":3.0,"tick":.5,"status":"slow","status_duration":1.2,"amount":.35,"visual":"cloud"},
	"Rock Scatter":{"mode":"area","anchor":"self","radius":3.2,"knockback":1.0},
	"Guard":{"mode":"buff","status":"shield","duration":6.0,"amount":.4},
	"Taunt":{"mode":"buff","status":"taunt","duration":5.0,"amount":1.0},
	"Fortify":{"mode":"buff","status":"shield","duration":6.0,"amount":.55},
	"Cover":{"mode":"buff","status":"shield","duration":6.0,"amount":.4,"ally":true},
	"Body Block":{"mode":"dash","speed":11.0,"radius":1.2,"knockback":1.6,"physical":true},
	"Shell Bash":{"mode":"dash","speed":10.0,"radius":1.0,"physical":true,"knockback":2.0},
	"Spin":{"mode":"field","anchor":"self_follow","radius":2.4,"duration":2.4,"tick":.35,"spin":true,"knockback":.6},
	"Hunker Down":{"mode":"buff","status":"cocoon","duration":4.0,"amount":.10},
	"Shelter":{"mode":"buff","status":"shield","duration":6.0,"amount":.35,"team":true},
	"Distract":{"mode":"buff","status":"taunt","duration":5.0,"amount":1.0},
	"Cheer":{"mode":"buff","status":"empower","duration":8.0,"amount":1.3,"team":true},
	"Encourage":{"mode":"buff","status":"haste","duration":6.0,"amount":1.0,"ally":true},
	"Copycat":{"mode":"copycat","radius":1.0},
	"Web Shot":{"mode":"projectile","speed":13.0,"radius":.24,"status":"slow","status_duration":2.0,"amount":.4,"visual":"vine"},
	"Web Snare":{"mode":"projectile","speed":10.0,"radius":.26,"status":"root","status_duration":2.5,"visual":"vine"},
	"Web Line":{"mode":"dash","speed":15.0,"radius":.5,"physical":true,"stop_at_target":true,"visual":"vine"},
	"Web Yank":{"mode":"projectile","speed":12.0,"radius":.24,"pull":2.8,"visual":"vine"},
	"Web Trap":{"mode":"mine","anchor":"self","radius":1.4,"trigger_radius":1.3,"delay":.4,"duration":10.0,"status":"root","status_duration":2.5},
	"Silk Sling":{"mode":"dash","speed":12.0,"radius":.9,"physical":true},
	"Tangle":{"mode":"field","anchor":"target","radius":2.4,"duration":3.0,"tick":.5,"status":"root","status_duration":1.0,"visual":"cloud"},
	"Poison Spit":{"mode":"projectile","speed":13.0,"radius":.24,"poison":4.0,"poison_chance":.35},
	"Gunk Glob":{"mode":"projectile","speed":11.0,"radius":.26,"splash":1.0,"status":"slow","status_duration":2.0,"amount":.35},
	"Corrode":{"mode":"projectile","speed":13.0,"radius":.24,"status":"defense_down","status_duration":4.0,"amount":.3},
	"Blinding Gunk":{"mode":"projectile","speed":13.0,"radius":.24,"status":"confuse","status_duration":3.0,"amount":.5},
	"Toxic Pop":{"mode":"projectile","speed":8.0,"radius":.22,"splash":1.6,"fuse":.6,"poison":4.0},
	"Noxious Cloud":{"mode":"field","anchor":"target","radius":2.4,"duration":3.5,"tick":.5,"poison":3.0,"poison_chance":.35,"visual":"cloud"},
	"Acid Rain":{"mode":"field","anchor":"target","radius":2.6,"delay":.4,"duration":4.0,"tick":.5,"poison":3.0,"visual":"rain"},
	"Nauseate":{"mode":"projectile","speed":13.0,"radius":.24,"status":"nauseated","status_duration":4.0,"amount":.3},
	"Fume Burst":{"mode":"area","anchor":"self","radius":2.6,"poison":4.0},
	"Poison Bomb":{"mode":"area","anchor":"target","radius":2.4,"delay":.7,"poison":5.0,"visual":"meteor"},
	"Gust":{"mode":"cone","angle":.65,"knockback":2.2},
	"Vacuum":{"mode":"area","anchor":"self","radius":3.2,"pull":2.6},
	"Crosswind":{"mode":"area","anchor":"self","radius":3.0,"knockback":1.8},
	"Updraft":{"mode":"area","anchor":"target","radius":1.6,"delay":.35,"launch":1.6,"visual":"pillar"},
	"Tailwind":{"mode":"buff","status":"hasten","duration":5.0,"amount":.35,"team":true},
	"Whirlwind":{"mode":"wave","speed":3.5,"width":2.0,"radius":.6,"carry":true,"knockback":.6},
	"Wind Wall":{"mode":"cone","angle":.9,"knockback":1.6},
	"Downdraft":{"mode":"area","anchor":"target","radius":2.0,"delay":.35,"knockback":.8},
	"Cyclone":{"mode":"field","anchor":"self_follow","radius":2.6,"duration":2.6,"tick":.3,"spin":true,"knockback":.7},
	"Air Burst":{"mode":"projectile","speed":12.0,"radius":.3,"splash":1.6,"knockback":2.2},
	"Deflate":{"mode":"area","anchor":"self","radius":3.6,"knockback":2.8},
	"Icicle Shot":{"mode":"projectile","speed":16.0,"radius":.2},
	"Ice Spike":{"mode":"area","anchor":"target","radius":1.0,"delay":.3,"visual":"pillar"},
	"Ice Wall":{"mode":"field","anchor":"target","radius":2.0,"duration":3.0,"tick":.5,"status":"slow","status_duration":1.5,"amount":.4,"visual":"cloud"},
	"Frost Patch":{"mode":"field","anchor":"target","radius":2.4,"duration":4.0,"tick":.5,"status":"slow","status_duration":1.5,"amount":.5,"visual":"cloud"},
	"Ice Cage":{"mode":"area","anchor":"target","radius":.8,"status":"root","status_duration":3.0,"visual":"roots"},
	"Glacier Rush":{"mode":"dash","speed":11.0,"radius":1.0,"physical":true},
	"Hail":{"mode":"field","anchor":"target","radius":2.7,"delay":.4,"duration":4.0,"tick":.45,"visual":"rain"},
	"Iceberg":{"mode":"area","anchor":"target","radius":1.4,"delay":.5,"launch":1.8,"visual":"pillar"},
	"Cold Snap":{"mode":"area","anchor":"self","radius":2.8,"status":"slow","status_duration":2.0,"amount":.4},
	"Icicle Mine":{"mode":"mine","anchor":"self","radius":2.0,"trigger_radius":1.3,"delay":.45,"duration":10.0,"status":"slow","status_duration":2.0,"amount":.4},
	"Shatter":{"mode":"area","anchor":"self","radius":3.0,"knockback":.8},
	"Honk":{"mode":"area","anchor":"self","radius":3.0,"status":"weaken","status_duration":4.0,"amount":.3,"interrupt":true},
	"Wingbeat":{"mode":"area","anchor":"self","radius":2.8,"knockback":1.8},
	"Feather Guard":{"mode":"buff","status":"shield","duration":6.0,"amount":.4},
	"Scare":{"mode":"area","anchor":"target","radius":1.2,"status":"confuse","status_duration":3.0,"amount":.8,"flee":true,"no_damage":true},
	"Escort":{"mode":"buff","status":"shield","duration":6.0,"amount":.4,"ally":true},
	"Alarm Honk":{"mode":"buff","status":"evade","duration":5.0,"amount":.35,"team":true},
	"Peck":{"mode":"peck","radius":.9},
	"Double Honk":{"mode":"area","anchor":"self","radius":3.8,"status":"weaken","status_duration":4.0,"amount":.3,"interrupt":true},
	"Two-Headed Watch":{"mode":"buff","status":"shield","duration":6.0,"amount":.4,"team":true},
	"Cross Peck":{"mode":"peck","radius":1.0},
	"Gaggle Rush":{"mode":"dash","speed":10.0,"radius":1.3,"physical":true,"knockback":1.2,"status":"weaken","status_duration":3.0,"amount":.25}
}

static func profile(move_name:String)->Dictionary:
	assert(PROFILES.has(move_name),"Missing gameplay definition: "+move_name)
	return PROFILES[move_name].duplicate(true)

static func supports(move_name:String,stone:String)->bool:
	var p:Dictionary=PROFILES[move_name];var mode:String=p.mode
	var support:bool=mode in ["heal","heal_field","buff","cleanse"]
	match stone:
		"echo","rush","link":return true
		"heavy":return mode!="cleanse"
		"reach":return not support and p.get("anchor","") not in ["self","self_follow"]
		"sharing":return support
		"chain","drain":return not support
		"split":return mode in ["projectile","wave","area","field","mine","firework"]
		"seeking":return mode=="projectile" or (mode=="wave" and p.get("visual","")=="bubble")
		"lingering":return p.has("duration") or p.has("burn") or p.has("status_duration") or p.has("trail")
		"blast":return p.has("splash") or mode in ["area","cone","line","wave","field","heal","heal_field","mine","firework"]
		"force":return p.has("release_knockback") or p.has("knockback") or p.has("pull") or p.has("launch") or p.get("physical",false)
	return false

static func is_support(move_name:String)->bool:
	return PROFILES[move_name].mode in ["heal","heal_field","buff","cleanse"]
